### ISSUE TITLE
Dawn of skyrim AI overhaul patch not available

### ISSUE THREAD

**Issue by psyycker** [apoapse1/Librum-for-Skyrim-VR#11]
Hi,

Thank you for this amazing work. I can't wait to be able to play Skyrim VR with your mod pack.
However, I'm having an issue.
At the moment, this mod (see title) is not available as it's been hidden by its creator.
See this link: https://www.nexusmods.com/skyrimspecialedition/mods/38527
It's then impossible to install the mod pack :( Would you have a work around to be able to finish the install?
Maybe if you have the archive, I could put it in the downloads folder, It could do the trick?

Thank you for your reply!

**Comment by believeinyuna** [comment]
the fix for this is on our discord server. https://discord.gg/56AV3Tzq
